### PR TITLE
Backport bundle fix from 1.21.2

### PR DESCRIPTION
**Pull request by octoturt**
i backported the [bundle workaround](https://github.com/TerminalMC/ClientSort/commit/c2e6dac9f361060e46acaa2b54930dba1e134b7c) from 1.21.2 to 1.21, as some other mods i'm using don't play nice with 1.21.2-3 yet and the server i'm playing on has the bundle datapack enabled. decided to put in a pull request in case anyone else is in a similar situation and wants to use it.

### CODE REVIEW

**Comment by NotRyken** [comment]
Just discovered a problem that I should've picked up before merging, in 1.21 bundles use RMB to pickup so the 1.21.2 fix actually breaks sorting on 1.21.

**Comment by NotRyken** [comment]
I think the most reasonable fix will be to add a config option to allow switching between RMB (1.21) and LMB (1.21.2) behavior.

**Comment by octoturt** [comment]
i haven't had any issues with it, but if you're experiencing them in testing then yeah that seems like the most reasonable fix

**Comment by NotRyken** [comment]
Did you test on 1.21 singleplayer?

**Comment by octoturt** [comment]
apologies for never responding, it's been a whirlwind couple of weeks for me. i only just tested it, and sure enough, it was still broken. looks like your changes fixed it, though, thank you!

**Pull request merged**
